### PR TITLE
Add Code of Conduct Linter

### LINKED ISSUE #79: Test for Code of Conduct
Steps to implement:
- Fork the repo
- Run `git checkout code-of-conduct` to make sure you are on the correct branch
- Run `make deps` or `npm install` if you do not have make installed
- Run `npm test` and watch tests fail
- Add `'Code of Conduct':/^CODEOFCONDUCT|CODE-OF-CONDUCT|CODE_OF_CONDUCT/i,` to the  `files` object in `./lib/lintFiles.js`

Some tests will also need to be updated:
- [helper.mockResponses.js](https://github.com/basicallydan/forkability/blob/master/spec/helper.mockResponses.js#L24)
 - Update the object to include: `path: 'CODEOFCONDUCT'`

- [app.test.js](https://github.com/basicallydan/forkability/blob/master/spec/app.test.js)
 - First three tests
   - Add `report.passes.should.containEql({ message: '.gitignore file' });`
    - Update `report.passes.should.have.a.lengthOf(8);` to 9
 - `'should warn about tag failures and include a fail badge'`
    - Update `report.passes.should.have.a.lengthOf(7);` to 8
 - `'should include a fail badge if < 90% of the items are successes'`
     - Update `report.passes.should.have.a.lengthOf(6);` to 7
 - `'should include a success badge if >= 90% of the items are successes'`
     - Update `firstCommitTreeBody` to include `path: 'codeofconduct.md'`
     - Update `report.failures.should.have.a.lengthOf(10);` to 11
 - `'should allow multiple languages to be used for linting - fails due to one of the languages'`
     - Update `report.failures.should.have.a.lengthOf(2);` to 3
 - `'should include a success badge if >= 90% of the items are successes'`
     - Update `firstCommitTreeBody` to include `path: 'codeofconduct.md'`
     - Update `report.failures.should.have.a.lengthOf(13);` to 14

### PR DESCRIPTION
**Pull request by Charlotteis**
Closes #79 & #67 

I did this PR as someone new to Forkability, but feel free to close if you wanted someone new to programming as a whole. Just trying to get a feel for node and this project :)

:christmas_tree: :santa:

### CODE REVIEW

**Comment by M-Zuber** [comment]
Looks great.
Being new to node and the project is good enough for this one. I expanded on that a little in #79

**Comment by M-Zuber** [comment]
Thank you very much!!
:tada:

**Comment by Charlotteis** [comment]
Wahoo!!

**Comment by basicallydan** [comment]
Legend, @Charlotteis! :christmas_tree: great PR-ing!

**Pull request merged**
