### PR TITLE
Version 0.18 release

### PR DESCRIPTION
**Pull request by basicallydan**
[@charlotteis](https://github.com/charlotteis) made codes of conduct a requirement. [@ExcaliburZero](https://github.com/ExcaliburZero) made the language option case-insensitive.

Updated the readme and changelog to reflect this.

:tada:

### CODE REVIEW

**Comment by M-Zuber** [comment]
:tada:

**Comment by basicallydan** [comment]
@M-Zuber Wait don't merge yet! Just had to add he compiled code. It's v0.18.1 now

**Comment by M-Zuber** [comment]
Not that we owe semver anything, but what mechanism do you use that forces the increment?

**Comment by basicallydan** [comment]
> never mind dumb me. npm right?

Correct! Not dumb. I go `npm minor|patch -m "blah blah"`

**Comment by M-Zuber** [comment]
Can I merge btw?

Maybe the steps for deployment/release should be written up somewhere?

**Comment by basicallydan** [comment]
Sure, go ahead and merge.

And they should be yes, especially since once we switch to an org I'm hoping you can also make releases :tada: if you want to anyway!

I'll write something up now and make another PR.

One of the ways my current job does PRs is to encourage others to do the merge as it means they've _probably_ had to have checked the code is a-ok. I think we should do it that way.

**Comment by M-Zuber** [comment]
>One of the ways my current job does PRs is to encourage others to do the merge as it means they've probably had to have checked the code is a-ok. I think we should do it that way.

I agree with this. Will check if there is a way to enforce that the merger can not be the PR author.

> And they should be yes, especially since once we switch to an org I'm hoping you can also make releases :tada: if you want to anyway!

Since we have decided on the previous item, then anyone who is a collab should be able to make a release - as it is not final until the PR is merged.
The npm story does need to be though out though.
Maybe the merger is the one that pushes to npm?
Otherwise if a PR is made but not merged, you have lost that version on npm. (there is a trick to publishing betas that can not be seen on the site, remind me and I'll tell you later)

**Comment by M-Zuber** [comment]
Oh, and maybe the @ forkability account on twitter should be telling people about the release?

**Comment by basicallydan** [comment]
> Oh, and maybe the @ forkability account on twitter should be telling people about the release?

On it. Will reply to other thing in a min.

**Comment by basicallydan** [comment]
> Will check if there is a way to enforce that the merger can not be the PR author.

Ah, I dunno if we wanna make it a requirement. Just in case!

> Since we have decided on the previous item, then anyone who is a collab should be able to make a release - as it is not final until the PR is merged.

Hmm, maybe. Publishing a release is quite a big deal though! I mean, it can make or break someone's dependent code. Quite a huge responsibility.

> Maybe the merger is the one that pushes to npm?

This sounds like a good plan, as long as the merger has `npm publish` access.

I gotta go teach a keen coder to get their Python environment set up now - I'll get around to the publishing guide soon! Maybe tonight or tomorrow morning. Ugh.

Real life ¯\_(ツ)_/¯

**Pull request merged**
