### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by andrew**
Noticed there were a few dependencies that were quite behind the latest so I updated those, plus rebuilt the shrinkwrap file too.

:christmas_tree:

### CODE REVIEW

**Comment by M-Zuber** [comment]
Just because, do you mind making sure instructions on creating/updating the shrinkwrap file are included somewhere?

**Comment by M-Zuber** [comment]
I'll merge this in the meantime as it all looks good
(node-watch is not doing so well though - it seems it does not actually output the result of the command it is running :disappointed: )

**Comment by andrew** [comment]
@M-Zuber The shrinkwrap interface is pretty terrible for updating it via the cli, so I went with:

    rm -rf node_modules/ npm-shrinkwrap.json && npm install && npm shrinkwrap

**Comment by M-Zuber** [comment]
maybe that could be added to the makefile?
I'll open a first-timers-only, I think.

**Comment by basicallydan** [comment]
Thanks @andrew :) you're a proper gent!

**Comment by M-Zuber** [comment]
I am now a maintainer of `npm-watch` and a new version was just released. Want to take care of it @andrew :stuck_out_tongue_winking_eye: ?

**Comment by andrew** [comment]
@M-Zuber https://github.com/basicallydan/forkability/pull/78

**Comment by M-Zuber** [comment]
:tada: you really are a machine :heart_eyes_cat:

**Pull request merged**
