### PR TITLE
Badges (#53)

### PR DESCRIPTION
**Pull request by basicallydan**
Right, I've added badges support by doing the following:

* The JavaScript API now returns an extra property in the object, `badge`, which has four of its own properties:
  * `type`, which is either `'ok'` or `'fail'` at the moment
  * `svg`, just a link to either the pass or fail SVG
  * `markdown`, a link to the Forkability page and the image in markdown
  * `html`, a link to the Forkability page and the image in html
* The type of badge is determined by the pass:failure ratio. If it's 90% or more (e.g. 9 passes, 1 failure or 10 passes, 1 failure, or 11 passes, 1 failure or 23 passes, 2 failures) it counts as a pass or `'ok'`. Anything *below* 90% is a fail, and they won't even be given a badge.
* The pages version now will include some text encouraging the user to "wear their badge with pride", and shows the badge in a little area of its own to highlight it, as well as giving them both the markdown and HTML (in that order) in `textarea`s whose contents can be selected using little "(select all)" links (I understand many people dislike select-on-click `textareas`)

So what I'd like to know from anybody reading this (mainly @M-Zuber I'm guessing) is some opinions about:

a) The new addition to the callback response in the API (e.g., what do we think of "ok" instead of "pass" because "pass" sounds a little too opinionated esp. considering 90% is OK)
b) The copy & layout on the page
c) Whether the SVG, markdown and HTML should be included in the command line API.
d) Should we try to encourage the user to pass by showing them what their badge could look like, or perhaps showing them a failure badge?

I shall eagerly await some input...!

### CODE REVIEW

**Comment by M-Zuber** [comment]
The code looks nice and simple, and easily refactorable to allow for more then two result types. 
I'll let you know what I think of the ui once I get a chance to see it :wink:

**Comment by basicallydan** [comment]
Cool. I might just go ahead and do it later today (it's morning now where I am in South Korea) if you're busy at the mo. Your opinion would be helpful but we can always change the UI a little bit later!

**Comment by M-Zuber** [comment]
I realized that I didn't actually respond to most of your points so here goes:
a) `ok` does sound more neutral, but I think that `pass` works well enough. Another option is to use `forkable` :wink: 
b) lets wait and see :grin: 
c) it would be nice to at least have an option to get the badge from the CL 
- this could allow easy integration of `forkablity` into CI builds, that probably do not want to fail if it is not forkable, but on success might want to ensure that the badge is present.
- (more flags anyone? [I have to find it, but I know a lib exists to make working with CL flags easier])
d) I would either show nothing (as you do now) or a failure badge. We don't want someone misunderstanding and putting in a pass badge inappropriately

**Comment by basicallydan** [comment]
a) Ah so we could just write "forkable" in the code?! Hmm. Yeah I guess so. Awfully domain-specific though. If we decide to change the name to something else (not sure how that would ever be possible since it's the best name ever :stuck_out_tongue_winking_eye: ) it'd cause problems. Gonna stick with `'ok'`
b) Cool
c) Very good point re: CI builds. I'll add it to the CL response. Just after I've finished watching Mr Robot. The flag library in Forkability is fine too, have a look at [this line](https://github.com/basicallydan/forkability/blob/master/index.js#L10), and [this line](https://github.com/basicallydan/forkability/blob/master/index.js#L47) for examples. Easy to add new flags/options.

Excellent answers, thank you.

**Comment by basicallydan** [comment]
AH I ACCIDENTALLY CLOSED.

**Comment by M-Zuber** [comment]
A) forkable is def the best name evah, but let's leave it it as you said
C) I believe what I saw was commander :wink:. Also Mr. Robot is def more important

**Comment by M-Zuber** [comment]
Any reason not to merge this?

**Comment by basicallydan** [comment]
Yes! Just wanted to put a flag in to show the badge in the command line,
but then I'll merge. I'm gonna get onto that tonight :) (it's only 7:45
where I am). I've finished all of Mr Robot I could get my hands on so
there's nothing else to do, really...

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
No pressure, I am just trying to clean up the issues list :)

**Comment by basicallydan** [comment]
I like it! Won't be long.

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by basicallydan** [comment]
So I've made it so that the badge output is very, very clearly a "failure" if it is one by making the text red and putting the word "failure". Let's put in a badge if anybody asks for it.

As well as that I've made the output a little more readable and useful. Have a look!

**Comment by basicallydan** [comment]
Sample output (from forkability)

```
# Forkability found 8 recommended features, and has 0 suggestions

# Features (8)
✓ Contributing document
✓ Readme document
✓ License document
✓ Changelog document
✓ .gitignore file
✓ Test suite
✓ All open issues have been acknowledged
✓ Tags are being used

---

# Suggestions (none)

---

# Forkability Badge (success)
## Just the SVG: 
https://img.shields.io/badge/forkable-yes-brightgreen.svg
## Markdown: 
[![This is a forkable respository](https://img.shields.io/badge/forkable-yes-brightgreen.svg)](https://basicallydan.github.io/forkability/?u=basicallydan&r=forkability)
## HTML: 
<a href="https://basicallydan.github.io/forkability/?u=basicallydan&r=forkability"><img alt="This is a forkable respository" src="https://img.shields.io/badge/forkable-yes-brightgreen.svg"></a>
```

**Comment by basicallydan** [comment]
Pretty sure you'll be cool with this ^^

**Comment by M-Zuber** [comment]
:ship: :+1: 
Great!!
Thank you.
There is still a question open for you at https://github.com/badges/shields/issues/502

**Comment by basicallydan** [comment]
https://basicallydan.github.io/forkability/?u=basicallydan&r=forkability

**Pull request merged**
