### PR TITLE
add test for .csproj that has a nested file

### PR DESCRIPTION
**Pull request by M-Zuber**
The test should prove that the linting works for nested files also

### CODE REVIEW

**Comment by basicallydan** [comment]
Hey @M-Zuber thanks for another PR! I'll give it a try and merge later! Sorry I didn't get to this sooner!

**Comment by M-Zuber** [comment]
It doesn't contain anything too important, so take your time. Cheers.

**Comment by M-Zuber** [comment]
So I've added a test that depends on recursion of the app.
I hope to implement (in at least a basic sense) a update to the app for this.

**Comment by M-Zuber** [comment]
Not relevant as of #46

**Pull request closed without merging**
