### PR TITLE
Recursive file fix

### PR DESCRIPTION
**Pull request by M-Zuber**
The `file linter` now checks for files deeper than the top layer.
The default depth is `3`

### CODE REVIEW

**Comment by M-Zuber** [comment]
There is still more testing to do, but this should provide an easy way to code review.

**Comment by M-Zuber** [comment]
I believe that this is implemented properly. If you could let me know what you think when you get a chance to look it over.
Cheers!

**Comment by basicallydan** [comment]
Will do! I'm currently packing for a holiday but when I'm done I'll have a
look :)

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by basicallydan** [comment]
Hey @M-Zuber! I hate to burst your bubble but it's not quite there. I think I know what to do to make it work, but like I said, I'm going on holiday so I probably won't get to it. Please don't feel obliged, you've already put so much work into this. However, I will tell you what is the matter in case you're motivated to do it!

In `csharp.test.js`, at line 168, put this instead of the `mockResponses` call that is already there.

```javascript
mockResponses({
	firstCommitTreeBody: {
		tree:[{
			path: 'source',
			type: 'tree',
			url: 'https://api.github.com/repos/thatoneguy/thatonerepo/git/trees/thirdSha'
		}, {
			path: 'main',
			type: 'tree',
			sha: 'secondSha',
			url: 'https://api.github.com/repos/thatoneguy/thatonerepo/git/trees/secondSha'
		}]
	}
});
```

You should see the arbitrary depth test failing. The reason is because in `app.js`, when the tree is looped through in `recursiveGetFileTrees`, the first item in the `localTree` array will cause a `promise` to be returned from the `recursiveGetFileTrees` function. What `recursiveGetFileTrees` should actually return is either a resolved promise, aka a response (as in the if statement `if (recursing === options.fileDepth) {` around line 73), or an array of promises, all of which need to be resolved. If you need pointing in the right direction, take a look at the promises library which is used in forkability, Q. Documentation for waiting for all promises in array resolved is [here](https://github.com/kriskowal/q#combination).

I tried doing that, but I got stuck in figuring out the instances where there were no more folders at the current level and the depth had not been reached. I'm pretty tired right now, so I'm gonna leave it, and maybe take a look while I'm on the plane or something :)

Sorry I've not done more to get this feature going, I'll do my best to help out when I can!

**Comment by M-Zuber** [comment]
On it. Enjoy your holiday :smile:

**Comment by M-Zuber** [comment]
After trying to fix this I noticed [this](https://developer.github.com/v3/git/trees/#get-a-tree-recursively) in the `github api`, which makes all this unnecessary. Closing, implementing and opening a new `PR`

**Pull request closed without merging**
