### PR TITLE
Fixes issues with compiling in order to run locally

### PR DESCRIPTION
**Pull request by M-Zuber**
Installs browserify and uglifyjs globally before compiling

### CODE REVIEW

**Comment by basicallydan** [comment]
I dunno... should we be messing with peoples' global modules? What if they have a specific version of `browserify` installed that they like?

Maybe we should put a warning/confirmation in first? Like [this][so]?

[so]: http://stackoverflow.com/a/1885534/403406

**Comment by M-Zuber** [comment]
That sounds good but we have to make sure there is a cross-plat way to do it.
Even better would be if there is a way to check if they are already installed. If they aren't ask the user permission.

The main problem here is that (at least as far as I can tell) you can not run browserify if it's not global. Therefore if someone is coming along and trying to run the command, having it in the global namespace is something they have to accept.

**Comment by basicallydan** [comment]
Are you sure they can't? If not, how come? Can't we install it and run it
from the node_modules folder, like we do with mocha in `package.json` with
`./node_modules/.bin/mocha`? `./node_modules/.bin/browserify` or something?

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
I'll try that out as soon as i can

**Comment by M-Zuber** [comment]
So forcing to use from node_modules works.
Closing this in favor of #88

**Comment by basicallydan** [comment]
Oh yay!

**Pull request closed without merging**
