### PR TITLE
Updated npm-watch and shrink-wrap file

### PR DESCRIPTION
**Pull request by andrew**
:snowboarder:

### CODE REVIEW

**Comment by M-Zuber** [comment]
It seems I was a bit hasty.
It would force node 5.2.
@basicallydan how do you feel about that?

**Comment by basicallydan** [comment]
@m-zuber what's wrong with travis.yaml being updated? I assume you mean we'd remove support for anything apart from 5.2.

**Comment by M-Zuber** [comment]
Yeah I was referring to only supporting node 5.2 and up

**Comment by basicallydan** [comment]
@M-Zuber Right. We eventually will need to go in this direction. But if we start bringing in modern node code into Forkability we also need to start transpiling with Babel or something because of the web app.

Apart from that I see no real problem in upgrading to 5.2. We're still in pre-v1 stage so it wouldn't break the rules of SemVer to do a minor update, but it would probably upset a few people who aren't ready to upgrade to 5.2. Not many though, I expect.

Am I right about that, re: semver? Opinions there would be helpful.

Can we get `.travis.yml` updated in this, @andrew?

**Comment by M-Zuber** [comment]
Right now it is a matter of dev dependencies, not a matter of our code so the transpiler issue should still be a bit of a ways off.
People who don't want to update yet, probably do not even have to if they really don't want to.
I believe you are correct about the semver

**Comment by andrew** [comment]
Just pushed an update to the .travis.yml config to only test against 5.2 and 5.3 :+1:

**Comment by basicallydan** [comment]
Ah, big step. Goodbye old node.

**Comment by basicallydan** [comment]
\*slowly downloads `node stable` over shitty Old Street Starbucks wifi\*

**Comment by M-Zuber** [comment]
:laughing: :joy:

**Pull request merged**
