### PR TITLE
Added config for travis-ci

### PR DESCRIPTION
**Pull request by andrew**
Now you can run the tests on http://travis-ci.org :dancer: 

Config tests against some of the more popular versions of node.

:santa:

### CODE REVIEW

**Comment by M-Zuber** [comment]
Awesome!!
Thank you very much

**Comment by andrew** [comment]
@M-Zuber you can now enable it from https://travis-ci.org/basicallydan/forkability

**Comment by M-Zuber** [comment]
I think @basicallydan is going to have to that..

**Comment by andrew** [comment]
Ah yeah, that's why I've moved my most popular repos to be owned by GitHub organizations, so multiple people can manage the administration of the repo and addons rather than just the owner.

**Comment by basicallydan** [comment]
@andrew @M-Zuber Yeaaaaaaaaaaaaaaaaaahhhhhh. Nice. Thanks for this. Enabled: https://travis-ci.org/basicallydan/forkability :trophy: 

@M-Zuber What @andrew said about moving to a GitHub org, I think it's a good idea, but not until maybe we've reached 100 stars. In terms of discoverability, at the moment being on my profile is probably pretty helpful because of Interfake. I know you suggested it a while go, what do you think about waiting til 100 stars? Arbitrary I know...

**Comment by M-Zuber** [comment]
100 :star: sounds good to me. 
Arbitrary things make life interesting :smile:

**Comment by andrew** [comment]
Submitted to reddit in an attempt to get a few more stars :wink: 

https://www.reddit.com/r/opensource/comments/3xup2f/forkability_a_linter_for_your_repository/

**Comment by basicallydan** [comment]
Haha thanks! I could've sworn I'd already put it on /r/opensource. Will
upvote!

**Comment by M-Zuber** [comment]
image
This is whats shown up so far :sob:

**Comment by basicallydan** [comment]
To be fair "A linter for your repository" is a bit vague. I just thought it sounded good. Thanks for sorting that out!

**Pull request merged**
