### PR TITLE
case insensitive comparison of login & username

### PR DESCRIPTION
**Pull request by Alshie**
fixes https://github.com/basicallydan/forkability/issues/59 by doing case insensitive comparison of username to given login

### CODE REVIEW

**Comment by M-Zuber** [comment]
Great! 

Please add some tests to [this file](https://github.com/basicallydan/forkability/blob/master/spec/lintIssues.test.js). 
If you need help, just ring

**Comment by Alshie** [comment]
Apologies! I have added tests now and ensured that they are passing.

**Comment by basicallydan** [comment]
Done. Thanks @Alshie, great PR! Thank you @M-Zuber for enforcing tests ^^ Merged, versioned, published.

**Comment by M-Zuber** [comment]
:thumbs-up:
Great work

**Pull request merged**
