### PR TITLE
Fix make

### PR DESCRIPTION
**Pull request by M-Zuber**
Use the locally installed browserify and uglifyjs

### CODE REVIEW

**Comment by basicallydan** [comment]
Totally works?

**Comment by basicallydan** [comment]
Okay I should try it myself haha. I'll do that a bit later today.

**Comment by M-Zuber** [comment]
I didn't check make serve, but make compile works. 

I made the changes here so you just have to pull the branch (& not my fork)

**Comment by basicallydan** [comment]
Im not sure if I like the install every time we compile thing bu I'll give it a go and see how we do :)

Looks good for now. :+1:

**Comment by basicallydan** [comment]
So happy you're a contributor :D no faffing around with forks.

**Comment by M-Zuber** [comment]
Doesn't npm recognize that packages are already installed and then doesn't re-download them?

**Comment by basicallydan** [comment]
Yeah it does do that, but it still seems to go through the process of checking for updates to any of the packages, on npm.org. Doesn't take too long.

I wonder, though, if `make compile' is really doing what it says on the tin if it's also resolving dependencies. What if I just want to quickly re-compile? Eh. I'm just not sure.

Am I wrong in assuming that the reason for this is to make sure browserify and uglify are installed? If so we could do:

```
npm install --only=development
```

...instead! Then, it won't try to re-download all the other stuff and it's the correct scope for what we're expecting.

Obviously, it won't compile properly if all the other dependencies are missing too, but should people who've only just cloned the repo expect to be able to compile without getting dependencies?

Alternatively, we could split this into two separate tasks: `make compile` and `make deps-and-compile` or something?

I hope I'm not overcomplicating this too much :(

**Comment by basicallydan** [comment]
@M-Zuber Okay, I have a suggestion:

`make deps` will do `npm install`
`make compile` will compile the code
`make` (the default) will do both of those things, and get the person who's contributing ready to go.

Thoughts?

**Comment by M-Zuber** [comment]
>EDIT: How about this – what was the intention of putting deps there?
Because I come from the .net world and when you compile it downloads missing packages 😉

Either way your last suggestion makes the most sense. We just have to also update the documentation to make it clear that in order to contribute you:
- fork
- download 
- make

**Comment by basicallydan** [comment]
Ah, okay. That makes sense.

We can still do that - it just means more make tasks. I'll do a branch and show you in an hour or so :+1:

**Pull request merged**
